### ISSUE TITLE
[Bug] 이미지 수정 오류

### ISSUE THREAD

**Issue by ReturnReason** [gaji-market/gaji-market#141]
![Honeycam 2023-01-21 06-40-41](https://user-images.githubusercontent.com/48672106/213810296-26b0e666-ec35-4184-a791-eadbffcb2709.gif)

아예 이미지를 새로 등록하는 경우는 상관없으나,
기존 이미지를 아무 변경사항 없이 수정하거나 
일부만 삭제하고 수정하는 경우 `이미지가 증발하는 현상`이 있습니다.

**Comment by ReturnReason** [comment]
> 이미지 첫 업로드 시 
![image](https://user-images.githubusercontent.com/48672106/213938881-e3eba3f4-bad6-4cbc-82ef-36c52c4c9318.png)

> 수정하기
![image](https://user-images.githubusercontent.com/48672106/213938906-e3931e80-1915-46df-99f4-d53c55bbc57c.png)

**Comment by ReturnReason** [comment]
@geondol 건형님! 늦은 시간이라 카톡으로 남기기에는 많이 장문이라서 놀라실까봐..ㅋㅋㅋㅠㅠ
이슈 코멘트로 남겨놓아요. 시간 나실 때 천천히 읽어보시고 답변 주세요. :)

## 가설
DB에 있는 이미지 URL을 참조하고 있는데 수정하기 버튼을 누르면 해당 이미지들이 DB에서 사라져서 이미지가 증발하는 것 같다는 가설(?)을 세워봤는데요, 
뇌피셜이지만 나름대로 고민해본 근거는 다음과 같습니다.

- 새로 등록하는 이미지들은 로컬에 있다가 s3에 등록되기 때문에 문제가 없습니다. 
- 하지만, 수정하기의 경우 s3의 URL을 받아와서 s3의 URL을 가지고 다시 보내게 되는데요. 
- 이 과정에서 `s3의 파일이 삭제되면서 문제가 발생하는 게 아닌가 하는 생각`이 들었습니다.

확실하진 않지만 코드를 계속 수정해보면서 파일 객체로 보내는 부분은
여러차례 다른 방법으로도 시도해봤지만 다른 문제를 찾지 못했어요...  😭😭 
등록하기와 동일하게 보내는데 왜 이미지만 이럴까........요..

> 아무튼, 만약 그렇다면 프론트에서 전달한 파일이 존재하는지 확인하는 과정이 필요할 것 같아요. 

## 해결 방안 제시

현재는 무조건 이전 파일을 삭제하는 방식(?맞나요??) 이라면 모두 다 삭제하고 다시 저장하는 방식이라 비효율적이긴 한데 지금 물불을 따질 때가 아니긴해서 가능하다면 이렇게라도 하면 좋겠지만, 이미지가 증발하는 이슈를 해결하기 위한 방법으로 `프론트에서 보내온 파일과 비교하는 과정`이 추가되면 어떨까 하는 생각이 들었어요.

> 예를들면, 
- 프론트에서 보내온 파일이 `다른 경우`에만 DB에 등록된 이미지를 삭제합니다.
- 프론트에서 보내온 파일과 현재 DB에 있는 파일이 `동일한 경우` 삭제 과정을 진행하지 않습니다.
- 프론트에서 보내온 파일과 현재 DB에 있는 파일이 `일부만 일치하는 경우` 일치하지 않는 파일만 찾아서 제거합니다.

## 의견

뇌피셜이라 확실하진 않아서 건형님의 의견도 들어보고 싶고,
**위와 같은 해결방안으로 구현 가능한지 여부도 궁금합니다!**

건형님께서도 고민해보시고 찾으신 다른 방법이 있다면 의견 보내주세요!
또, 제가 제안한 방법이 불가능하다 하신다면 다른 방안을 다시 고민해보면 좋을 것 같아요!! 😊

일단 제가 생각한 방법은 저게 아니면..
차선책으로 일단 보내온 파일을 저장하고 이전 파일을 삭제하는 방법..?도 가능할지는 모르겠는데
`선 저장 후 삭제`가 된다면 어떤 결과가 나오는지도 궁금하긴 하네요...ㅎㅎ

**Comment by geondol** [comment]
음.. 가설에 대해 먼저 얘기를 하자면 s3에 이미지저장 자체는 이유님이 보내주신 파일로만 저장을 하고있어서 삭제쪽이랑은 아예 다른부분인데 파일 삭제 안하고 하는것도 한번 테스트 해보면 좋을꺼같긴합니다! 

해결방안 제시쪽은 어제 제가 얘기 했던 부분이랑 똑같습니다 저렇게 하는 방법도 있을꺼같은데 지금당장은 모르겠고 한번 해봐야 알것같다한 부분이 해결방안 부분입니다 설명하기가 너무 헷갈려서 제가 설명을 뒤죽박죽 했다봐여 ㅋㅋㅋㅋㅋㅋㅋ

cors부분은 한번 찾아보겠습니다!

**Comment by ReturnReason** [comment]
> 음.. 가설에 대해 먼저 얘기를 하자면 s3에 이미지저장 자체는 이유님이 보내주신 파일로만 저장을 하고있어서 삭제쪽이랑은 아예 다른부분인데 파일 삭제 안하고 하는것도 한번 테스트 해보면 좋을꺼같긴합니다!
> 
> 해결방안 제시쪽은 어제 제가 얘기 했던 부분이랑 똑같습니다 저렇게 하는 방법도 있을꺼같은데 지금당장은 모르겠고 한번 해봐야 알것같다한 부분이 해결방안 부분입니다 설명하기가 너무 헷갈려서 제가 설명을 뒤죽박죽 했다봐여 ㅋㅋㅋㅋㅋㅋㅋ
> 
> cors부분은 한번 찾아보겠습니다!

헙 그렇군요 ! 어제 여러 방면으로 시도해보다 혹시?했었던 부분인데 삭제랑은 다른 부분이었군요. 아쉽습니당 ㅠㅠㅠ
그렇다면 제가 다른 방법으로 한번 시도해보고 싶은게 있긴 합니당! 되면 좋을 텐데요.....!
건형님이 `s3 CORS` 설정만 해주시면 시도해보고 다시 말씀드리겠습니다!!
