### ISSUE TITLE
가지마켓 배포 관련 이슈

### ISSUE THREAD

**Issue by vjvl95** [gaji-market/gaji-market#168]
안녕하십니까 팀원분들 AWS 배포 관련해서 한가지 문제가 생겨서 이슈를 쓰게 되었습니다.

![image](https://user-images.githubusercontent.com/62174495/219402622-498c55da-2447-4d6b-802e-d38885c015cd.png)

![image](https://user-images.githubusercontent.com/62174495/219402805-a22c2ee3-88c6-4004-b14a-c91c5d2f6497.png)

원래 s3로 배포하게 되면 아래와 같은 주소로 배포가 되게 됩니다.

![image](https://user-images.githubusercontent.com/62174495/219403402-b82e0bd1-12d7-40a6-8c9e-86053d0194ee.png)

하지만 제가 배포를 할 때 router 53이라는 것을 사용하여서 URL을 바꾸는 작업을 하였습니다.
여기서 이제 문제가 발생하게 되는데 router 53은 한 달에 사용료가 0.5달러가 청구가 됩니다.
제가 계속 부담을 하는건 무리가 있는것 같아서 여기다가 글을 쓰게 되었습니다.

현재 제가 생각한 해결 방법은 두 가지입니다.
1. router 53을 쓰지 않고 기존 s3 url을 사용한다.(이 경우 이때까지 청구된 1300원 정도는 제가 부담을 하겠습니다. 과금이 되는지 모르고 팀원분들과 상의없이 제가 사용하였기 때문에 이 금액에 대해서 나누어서 내자고 아닌 것 같다는 판단을 하였습니다.) 

2. 만약 gajimarket.shop url을 계속 사용 한다고 하면 저희가 돈을 모아서 비용을 분담해야 할 것 같습니다. 제가 가비아에서 현재 사용 중인 도메인을 1년 기간동안 샀으니 한달에 0.5달러가 청구된다는 가정하에 6달러 정도의 비용이 나올걸로 예상됩니다(환율이 계속 바뀌어서 한달에 내는 돈이 달라집니다). 현재 원 달러 환율이 1,291원입니다. 만약 2번 방법으로 가게 되면 한 사람당 얼마를 낼지도 정해야 할 것 같습니다.

프로젝트가 다 끝난 줄 알고 있었는데 이메일로 과금 메일이 왔길래 황급히 생각을 해보았습니다.
보시고 밑에 댓글을 달아주셔도 되고 단톡방에서 의견을 이야기 해주시면 감사하겠습니다.

**Comment by ReturnReason** [comment]
일단 제 의견을 말씀드리자면 소액이라 상관없을 것 같습니다.
포폴로 사용될 프로젝트라면 이상한 주소보다는 도메인을 쓰는 편이 좋다고 생각해요.
매년 연장할 필요는 없을 것 같고, 한 `2년 정도` 사용하면 되지 않을까 싶어요.
